### ISSUE TITLE
Double tapping a Confirm Button has unexpected behaviour

### ISSUE THREAD

**Issue by SpacyRicochet** [mikeahmarani/MAConfirmButton#4]
Double tapping (or tapping twice quickly) on an MAConfirmButton (from your Sample) causes the button to grow larger than expected in the confirm state.

**Comment by SpacyRicochet** [comment]
I have been trying to remove this behaviour by setting `self.userInteractionEnabled = NO` and having the `touchesBegan:` and `touchesEnded:` only act when this is set to `YES`. I set it back after in a completion block for the animation that occurs after the animation is finished, but to no avail (see below).

https://gist.github.com/1633825

**Comment by mikeahmarani** [comment]
Hey, sorry it took me so long to get around to this bug. It's fixed. You were close, there is a second CATransaction within the completion block of the first. That is where `self.userInteractionEnabled = YES` needs to be set. Take a look at the recent push changes :)
