### ISSUE TITLE
Triple Tapping or more in button has unexpected behaviour

### ISSUE THREAD

**Issue by winardi** [mikeahmarani/MAConfirmButton#6]
When triple tapping or more in button, then click outside of the button will make unexpected behaviour

I think it's because the cancelOverlay added more than once

I try to add this code before adding cancelOverlay button in touchesEnded function and it runs well :
if(cancelOverlay!=nil){
    [cancelOverlay removeFromSuperview];
    cancelOverlay = nil;
}

**Comment by mikeahmarani** [comment]
That doesn't fix it either. This whole class needs a rewrite -_-

I'm working on it now.
